name: Trigger Cypress Tests

on:
  push:
    branches:
      - beta

jobs:
  dispatch-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger tests in QAtests
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: Marevo7/QAtests
          event-type: run-tests
